export const data = {
    words:[
        // 'asus',
        // 'lenovo',
        // 'oppo',
        // 'mi',
        // 'sony-xperia-z2',
        // 'iphone-15',
        // 'iphone-16'
        'hp 15',
        'realme NARZO 80',
        'vivo T4x',
        'oppo F31 Pro+',
        'jbl Tune ANC',
        'sony WH-CH520',
        'zebronics thunder',
        'boAt Rockerz 411',
        'noise Master Buds',
        'nikon D7500',
        'nikon Z50',
        'canon EOS R50',
        'canon EOS R7',
        'canon EOS R50',
        'hp victus',
        'lenovo ideapad slim 3',
        'apple macBook pro',
        'apple macBook air',
        'nothing phone (3A) 5G',
        'samsung galaxy s25 ultra',
        'samsung galaxy Z-fold6',
        'samsung galaxy A35',
        'samsung galaxy S24 FE',
        'iphone 12',
        'iphone 16',
        'iphone 14',
        'iphone 13',
        'iphone 15',
        'iphone 17'
    ]
}